export const products = [
    {
      id: 1,
      title: "20kg DUMBBELL SET",
      description: "Silver in color",
      price: "7500",
      img: "./images/dumbbell1.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "10kg DUMBBELL SET",
      description: "Black in color",
      price: "5500",
      img: "./images/dumbbell2.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "TUNTURI FITNESSMAT PRO MAT 140 - GREEN",
      description: "The solid and thick material ensures a comfortable lying down posture during your floor exercises. green in color",
      price: "3500",
      img: "./images/mat1.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "TUNTURI FITNESSMAT PRO MAT - BLACK",
      description: "The solid and thick material ensures a comfortable lying down posture during your floor exercises. black in color",
      price: "5800",
      img: "./images/mat2.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "10kg DUMBBELL SET",
      description: "Black in color",
      price: "5500",
      img: "./images/dumbbell2.jpg",
      quantity: 1,
    },
    {
      id: 6,
      title: "10kg DUMBBELL SET",
      description: "Black in color",
      price: "5500",
      img: "./images/dumbbell2.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "10kg DUMBBELL SET",
      description: "Black in color",
      price: "5500",
      img: "./images/dumbbell2.jpg",
      quantity: 1,
    },
    {
      id: 8,
        title: "10kg DUMBBELL SET",
        description: "Black in color",
        price: "5500",
        img: "./images/dumbbell2.jpg",
        quantity: 1,
    },
    {
      id: 9,
      title: "10kg DUMBBELL SET",
      description: "Black in color",
      price: "5500",
      img: "./images/dumbbell2.jpg",
      quantity: 1,
    },
  ];